/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        primary: "#2d4055",
        "on-primary": "#ffffff",
        "primary-container": "#44576d",
        "on-primary-container": "#b9cce6",
        "primary-fixed": "#d0e4ff",
        "primary-fixed-dim": "#b4c8e2",
        "inverse-primary": "#b4c8e2",
        secondary: "#466271",
        "on-secondary": "#ffffff",
        "secondary-container": "#c9e7f8",
        "on-secondary-container": "#4c6877",
        tertiary: "#344047",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#4b575f",
        "on-tertiary-container": "#c0ccd5",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        surface: "#f9f9f9",
        "surface-dim": "#dadada",
        "surface-bright": "#f9f9f9",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f4f3f3",
        "surface-container": "#eeeeee",
        "surface-container-high": "#e8e8e8",
        "surface-container-highest": "#e2e2e2",
        "surface-variant": "#e2e2e2",
        "surface-tint": "#4d6076",
        background: "#f9f9f9",
        "on-background": "#1a1c1c",
        "on-surface": "#1a1c1c",
        "on-surface-variant": "#43474c",
        "inverse-surface": "#2f3131",
        "inverse-on-surface": "#f1f1f1",
        outline: "#74777d",
        "outline-variant": "#c4c6cd",
      },
      borderRadius: {
        sm: 4,
        DEFAULT: 8,
        md: 12,
        lg: 16,
        xl: 24,
        full: 9999,
      },
      spacing: {
        xs: 4,
        base: 8,
        sm: 12,
        gutter: 16,
        margin: 20,
        md: 24,
        lg: 40,
        xl: 64,
      },
      fontFamily: {
        sans: ["HankenGrotesk_400Regular"],
        medium: ["HankenGrotesk_500Medium"],
        semibold: ["HankenGrotesk_600SemiBold"],
        bold: ["HankenGrotesk_700Bold"],
        black: ["HankenGrotesk_800ExtraBold"],
      },
    },
  },
};